urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

from mezzanine.core.views import direct_to_template


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = patterns("",

    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

#    url("^$", direct_to_template, {"template": "index.html"}, name="home"),
    url("^", include("viddypull.urls")),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part. Make
    # sure to uncheck "show in navigation" when you create the page,
    # since the link to the homepage is always hard-coded into all the
    # page menus that display navigation on the site. Also note that
    # the normal rule of adding a custom template per page with the
    # template name using the page's slug doesn't apply here, since
    # we can't have a template called "/.html" - so for this case, the
    # template "pages/index.html" can be used.

    # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler500 = "mezzanine.core.views.server_error"

viddypull/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()

from mezzanine.core.views import direct_to_template

urlpatterns = patterns('viddypull.views',
    url("^$", "home", name="home"),
    url("^details/(?P<viddy_id>\d+)/$", "viddy_details", name="viddy_details"),
    url("^tag/(?P<tag_id>[\w-]+)/$", "viddys_by_tag", name="viddys_by_tag"),
)

viddypull/models.py
from django.db import models
from mezzanine.core.models import Displayable, RichTextField
from mezzanine.generic.fields import CommentsField, RatingField
from django.utils.translation import ugettext_lazy as _

class Viddy(Displayable):
#    user = models.ForeignKey(User)
    comment_count = models.IntegerField(blank=True, null=True, verbose_name="Comment Count")
    like_count = models.IntegerField(blank=True, null=True, verbose_name="Like Count")
    video_id = models.CharField(max_length=400, verbose_name="Video ID", blank=True, null=True)
    video_source = models.CharField(max_length=400, verbose_name="Video Source", blank=True, null=True)
    thumbnail = models.CharField(max_length=400, verbose_name="Thumbnail", blank=True, null=True)
    size = models.CharField(max_length=400, verbose_name="Size", blank=True, null=True)
    video_description = models.TextField(verbose_name="Video Description", blank=True, null=True)
    viddy_user = models.CharField(max_length=200, verbose_name="Viddy Username", blank=True, null=True)
    viddy_user_id = models.CharField(max_length=200, verbose_name="Viddy User ID", blank=True, null=True)
    viddy_user_thumbnail = models.CharField(max_length=200, verbose_name="Viddy User", blank=True, null=True)
    viddy_user_profile = models.CharField(max_length=200, verbose_name="Viddy User Profile", blank=True, null=True)

    @models.permalink
    def get_absolute_url(self):
        return ('viddypull.views.viddy_details', [self.id])

    def __unicode__(self):
        return self.title


class Tag(models.Model):
    viddy = models.ForeignKey(Viddy, verbose_name="Video", blank=True, null=True)
    tag = models.CharField(max_length=200, verbose_name="Tag", blank=True, null=True)
    tag_id = models.CharField(max_length=200, verbose_name="Tag ID", blank=True, null=True)
    media_id = models.CharField(max_length=200, verbose_name="Video ID", blank=True, null=True)

viddypull/views.py
from viddypull.models import *

from django.shortcuts import render_to_response, get_object_or_404, get_list_or_404
from django.template import RequestContext
from django import forms
from django.http import HttpResponse, Http404, HttpResponsePermanentRedirect, HttpResponseRedirect
from mezzanine.utils.views import paginate
from django.db.models import Count
from django.contrib.auth.decorators import login_required

@login_required()
def home(request):
    sort_criteria = request.GET.get("sortby", '-like_count')
    viddy = Viddy.objects.all().order_by(sort_criteria)
    viddy = paginate(viddy,
                        request.GET.get("page", 1),
                        27, 16)

    tag_count = Tag.objects.values('tag', 'tag_id').annotate(tcount=Count('tag_id')).order_by('-tcount')[:100]

    return render_to_response('index.html',{"viddy":viddy, 'tag_count':tag_count},
                context_instance=RequestContext(request))


@login_required()
def viddy_details(request, viddy_id):
    viddy = Viddy.objects.get(pk=viddy_id)
    return render_to_response('pages/details.html',{"viddy":viddy},
                context_instance=RequestContext(request))


@login_required()
def viddys_by_tag(request, tag_id):
    sort_criteria = request.GET.get("sortby", '-viddy__like_count')
    tag = Tag.objects.filter(tag_id=tag_id).order_by(sort_criteria)
    tag = paginate(tag,
                        request.GET.get("page", 1),
                        27, 16)

    tag_count = Tag.objects.values('tag', 'tag_id').annotate(tcount=Count('tag_id')).order_by('-tcount')[:100]

    return render_to_response('pages/list-by-tag.html',{'tag':tag, 'tag_count':tag_count},
                context_instance=RequestContext(request))

templates/base.html
<!DOCTYPE html>
{% load pages_tags mezzanine_tags i18n %}
<html>
<head>

<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width">
<meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
<meta name="description" content="{% block meta_description %}{% endblock %}">
<title>{% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}</title>
<link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.ico">

{% ifinstalled mezzanine.blog %}
<link rel="alternate" type="application/rss+xml" title="RSS" href="{% url blog_post_feed "rss" %}">
<link rel="alternate" type="application/atom+xml" title="Atom" href="{% url blog_post_feed "atom" %}">
{% endifinstalled %}

{% compress css %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.css">
<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.responsive.css">
<link rel="stylesheet" href="{{ STATIC_URL }}css/mezzanine.css">
{% ifinstalled cartridge.shop %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/cartridge.css">
{% endifinstalled %}
{% block extra_css %}{% endblock %}
{% endcompress %}

{% compress js %}
<script src="{{ STATIC_URL }}mezzanine/js/{{ settings.JQUERY_FILENAME }}"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
<script>
$(function() {
    $('.middleinput:text, textarea').addClass('xlarge');
    $('.control-group label').addClass('control-label');
});
</script>
{% block extra_js %}{% endblock %}
{% endcompress %}
<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

{% block extra_head %}{% endblock %}

</head>
<body id="{% block body_id %}body{% endblock %}">

<div class="navbar">
<div class="navbar-inner">
<div class="container">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </a>
    {% if settings.SITE_TITLE %}<a class="brand" href="/">{{ settings.SITE_TITLE }}</a>{% endif %}
    {% if settings.SITE_TAGLINE %}<p class="tagline">{{ settings.SITE_TAGLINE }}</p>{% endif %}
    <div class="nav-collapse">
        <form action="{% url search %}" class="navbar-search pull-right">
        <input class="search-query" placeholder="{% trans "Search" %}" type="text" name="q" value="{{ request.REQUEST.q }}">
        </form>
        {% page_menu "pages/menus/dropdown.html" %}
    </div>
</div>
</div>
</div>

<div class="container">

{% nevercache %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}" data-alert="alert">
<a class="close" href="#" onclick="$(this).parent().fadeOut('fast'); return false;">×</a>{{ message }}
</div>
{% endfor %}
{% endnevercache %}


<h6>{% block title %}{% endblock %}</h6>

<ul class="breadcrumb">
{% spaceless %}
{% block breadcrumb_menu %}{% page_menu "pages/menus/breadcrumb.html" %}{% endblock %}
{% endspaceless %}
</ul>

</div>

<div class="container">

<div class="row">

{#<div class="span2 left">#}
{#    {% block left_panel %}#}
{#    <div class="panel tree">{% page_menu "pages/menus/tree.html" %}</div>#}
{#    {% endblock %}#}
{#</div>#}

<div class="span9 middle">
    {% block main %}{% endblock %}
</div>

<div class="span3 right">
    {% block right %}{% endblock %}
{#    {% nevercache %}#}
{#    {% include "includes/user_panel.html" %}#}
{#    {% endnevercache %}#}
{#    <div class="panel">#}
{#    {% block right_panel %}#}
{#    {% ifinstalled mezzanine.twitter %}#}
{#    {% include "twitter/tweets.html" %}#}
{#    {% endifinstalled %}#}
{#    {% endblock %}#}
{#    </div>#}
</div>

</div>

</div>

<footer>
<div class="container">
{#{% page_menu "pages/menus/footer.html" %}#}
{#<br style="clear:both">#}
{#<p>#}
{#    {% trans "Powered by" %}#}
{#    <a href="http://mezzanine.jupo.org">Mezzanine</a>{% ifinstalled cartridge.shop %},#}
{#    <a href="http://cartridge.jupo.org">Cartridge</a>{% endifinstalled %}#}
{#    {% trans "and" %}#}
{#    <a href="http://www.djangoproject.com">Django</a>#}
{#    <span class="separator">|</span>#}
{#    {% trans "Theme by" %} <a href="http://twitter.github.com/bootstrap/">Bootstrap</a>#}
{#    {% ifinstalled mezzanine.mobile %}#}
{#    <span class="separator">|</span>#}
{#    <a href="{% url set_device "mobile" %}?next={{ request.path }}">{% trans "View Mobile Site" %}</a>#}
{#    {% endifinstalled %}#}
{#</p>#}
</div>
</footer>

{% include "includes/footer_scripts.html" %}

</body>
</html>

templates/blog/blog_post_detail.html
{% extends "blog/blog_post_list.html" %}
{% load mezzanine_tags comment_tags keyword_tags rating_tags i18n %}

{% block meta_title %}{{ blog_post.meta_title }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for blog_post as tags %}
{% for tag in tags %}{% if not forloop.first %}, {% endif %}{{ tag }}{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ blog_post.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% editable blog_post.title %}{{ blog_post.title }}{% endeditable %}
{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
<li class="active">{{ blog_post.title }}</li>
{% endblock %}

{% block main %}

<h6>
    {% trans "Posted by" %}:
    {% with blog_post.user as author %}
    <a href="{% url blog_post_list_author author %}">{{ author.get_full_name|default:author.username }}</a>
    {% endwith %}
    {{ blog_post.publish_date|timesince }} {% trans "ago" %}
</h6>
<p>
    {% if blog_post.allow_comments %}(<a href="#comments">{% spaceless %}
        {% blocktrans count blog_post.comments_count as comments_count %}1 comment{% plural %}{{ comments_count }} comments{% endblocktrans %}
    {% endspaceless %}</a>){% endif %}
</p>

{% if blog_post.featured_image %}
<p><img src="{{ MEDIA_URL }}{% thumbnail blog_post.featured_image 600 0 %}"></p>
{% endif %}

{% editable blog_post.content %}
{{ blog_post.content|richtext_filter|safe }}
{% endeditable %}

{% keywords_for blog_post as tags %}
{% if tags %}
{% spaceless %}
<ul class="unstyled tags">
    <li>{% trans "Tags" %}:</li>
    {% for tag in tags %}
    <li><a href="{% url blog_post_list_tag tag.slug %}">{{ tag }}</a></li>
    {% endfor %}
</ul>
{% endspaceless %}
{% endif %}

{% rating_for blog_post %}

{% set_short_url_for blog_post %}
<a class="btn small primary share-twitter" target="_blank" href="http://twitter.com/home?status={{ blog_post.short_url|urlencode }}%20{{ blog_post.title|urlencode }}">{% trans "Share on Twitter" %}</a>
<a class="btn small primary share-facebook" target="_blank" href="http://facebook.com/sharer.php?u={{ request.build_absolute_uri }}&amp;t={{ blog_post.title|urlencode }}">{% trans "Share on Facebook" %}</a>

{% if blog_post.allow_comments %}{% comments_for blog_post %}{% endif %}

{% endblock %}

templates/blog/blog_post_list.html
{% extends "base.html" %}
{% load i18n mezzanine_tags blog_tags keyword_tags disqus_tags %}

{% block meta_title %}{% if page %}{{ page.richtextpage.meta_title }}{% else %}{% trans "Blog" %}{% endif %}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for page as keywords %}
{% for keyword in keywords %}
    {% if not forloop.first %}, {% endif %}
    {{ keyword }}
{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ page.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% if page %}
{% editable page.title %}{{ page.title }}{% endeditable %}
{% else %}
{% trans "Blog" %}
{% endif %}
{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
{% if tag or category or year or month or author %}
<li>{% spaceless %}
{% if tag %}
    {% trans "Tag:" %} {{ tag }}
{% else %}{% if category %}
    {% trans "Category:" %} {{ category }}
{% else %}{% if year or month %}
    {% if month %}{{ month }}, {% endif %}{{ year }}
{% else %}{% if author %}
    {% trans "Author:" %} {{ author.get_full_name|default:author.username }}
{% endif %}{% endif %}{% endif %}{% endif %}
{% endspaceless %}
</li>
{% endif %}
{% endblock %}

{% block main %}

{% if tag or category or year or month or author %}
    <p>
    {% if tag %}
        {% trans "Viewing posts tagged" %} {{ tag }}
    {% else %}{% if category %}
        {% trans "Viewing posts for the category" %} {{ category }}
    {% else %}{% if year or month %}
        {% trans "Viewing posts from" %} {% if month %}{{ month }}, {% endif %}
        {{ year }}
    {% else %}{% if author %}
        {% trans "Viewing posts by" %}
        {{ author.get_full_name|default:author.username }}
    {% endif %}{% endif %}{% endif %}{% endif %}
    </p>
{% else %}
    {% if page %}
    {% editable page.richtextpage.content %}
    {{ page.richtextpage.content|safe }}
    {% endeditable %}
    {% endif %}
{% endif %}

{% for blog_post in blog_posts.object_list %}
{% editable blog_post.title blog_post.publish_date %}
<h2>
    <a href="{{ blog_post.get_absolute_url }}">{{ blog_post.title }}</a>
</h2>
<h6>
    {% trans "Posted by" %}:
    {% with blog_post.user as author %}
    <a href="{% url blog_post_list_author author %}">{{ author.get_full_name|default:author.username }}</a>
    {% endwith %}
    {% if blog_post.category_list %}
    {% trans "in" %}
    {% for category in blog_post.category_list %}
    <a href="{% url blog_post_list_category category.slug %}">{{ category }}</a>
    {% endfor %}
    {% endif %}
    {{ blog_post.publish_date|timesince }} {% trans "ago" %}
</h6>
{% endeditable %}

{% if blog_post.featured_image %}
<img class="featured-thumb" src="{{ MEDIA_URL }}{% thumbnail blog_post.featured_image 90 90 %}">
{% endif %}

{% editable blog_post.content %}
{{ blog_post.description_from_content|safe }}
{% endeditable %}

<p class="blog-list-detail">
    {% if blog_post.keyword_list %}
    {% trans "Tags" %}:
    {% spaceless %}
    {% for tag in blog_post.keyword_list %}
    <a href="{% url blog_post_list_tag tag.slug %}" class="tag">{{ tag }}</a>
    {% endfor %}
    {% endspaceless %}
    <br>
    {% endif %}
    <a href="{{ blog_post.get_absolute_url }}">{% trans "read more" %}</a>
    /
    {% if settings.COMMENTS_DISQUS_SHORTNAME %}
    <a href="{{ blog_post.get_absolute_url }}#disqus_thread"
        data-disqus-identifier="{% disqus_id_for blog_post %}">
        {% trans "Comments" %}
    </a>
    {% else %}
    <a href="{{ blog_post.get_absolute_url }}#comments">
        {% blocktrans count blog_post.comments_count as comments_count %}1 comment{% plural %}{{ comments_count }} comments{% endblocktrans %}
    </a>
    {% endif %}
</p>
{% endfor %}

{% pagination_for blog_posts %}

{% if settings.COMMENTS_DISQUS_SHORTNAME %}
{% include "generic/includes/disqus_counts.html" %}
{% endif %}

{% endblock %}

{% block right_panel %}
{% include "blog/includes/filter_panel.html" %}
{% endblock %}

templates/blog/includes/filter_panel.html
{% load blog_tags keyword_tags i18n %}

{% blog_recent_posts 5 as recent_posts %}
{% if recent_posts %}
<h3>{% trans "Recent Posts" %}</h3>
<ul class="unstyled recent-posts">
{% for recent_post in recent_posts %}
<li><a href="{{ recent_post.get_absolute_url }}"
    >{{ recent_post.title }}</a></li>
{% endfor %}
</ul>
{% endif %}

{% blog_months as months %}
{% if months %}
<h3>{% trans "Archive" %}</h3>
{% for month in months %}
    {% ifchanged month.date.year %}
        {% if not forloop.first %}</ul>{% endif %}
        <h6>{{ month.date.year }}</h6><ul class="unstyled">
    {% endifchanged %}
    <li><a href="{% url blog_post_list_month year=month.date.year month=month.date.month %}"
        >{{ month.date|date:"F" }}</a> ({{ month.post_count }})</li>
{% endfor %}
</ul>
{% endif %}

{% blog_categories as categories %}
{% if categories %}
<h3>{% trans "Categories" %}</h3>
<ul class="unstyled">
{% for category in categories %}
<li><a href="{% url blog_post_list_category category.slug %}"
    >{{ category }}</a> ({{ category.post_count }})</li>
{% endfor %}
</ul>
{% endif %}

{% keywords_for blog.blogpost as tags %}
{% if tags %}
<h3>{% trans "Tags" %}</h3>
<ul class="unstyled tags">
{% for tag in tags %}
<li>
    <a href="{% url blog_post_list_tag tag.slug %}"
        class="tag-weight-{{ tag.weight }}">{{ tag }}</a>
    ({{ tag.item_count }})
</li>
{% endfor %}
</ul>
{% endif %}

{% blog_authors as authors %}
{% if authors %}
<h3>{% trans "Authors" %}</h3>
<ul class="unstyled">
{% for author in authors %}
    <li><a href="{% url blog_post_list_author author.username %}"
        >{{ author.get_full_name|default:author.username }}</a>
        ({{ author.post_count }})</li>
{% endfor %}
</ul>
{% endif %}

<h3>{% trans "Feeds" %}</h3>
{% if tag %}
    <a href="{% url blog_post_feed_tag tag "rss" %}">{% trans "RSS" %}</a> /
    <a href="{% url blog_post_feed_tag tag "atom" %}">{% trans "Atom" %}</a>
{% endif %}
{% if category %}
    <a href="{% url blog_post_feed_category category.slug "rss" %}">{% trans "RSS" %}</a> /
    <a href="{% url blog_post_feed_category category.slug "atom" %}">{% trans "Atom" %}</a>
{% endif %}
{% if author %}
    <a href="{% url blog_post_feed_author author.username "rss" %}">{% trans "RSS" %}</a> /
    <a href="{% url blog_post_feed_author author.username "atom" %}">{% trans "Atom" %}</a>
{% endif %}
{% if not tag and not category and not author %}
    <a href="{% url blog_post_feed "rss" %}">{% trans "RSS" %}</a> /
    <a href="{% url blog_post_feed "atom" %}">{% trans "Atom" %}</a>
{% endif %}

templates/generic/comments.html
{% extends "base.html" %}

{% load mezzanine_tags comment_tags keyword_tags %}

{% block meta_title %}{{ obj }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for obj as tags %}
{% for tag in tags %}{% if not forloop.first %}, {% endif %}{{ tag }}{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ obj.description }}
{% endmetablock %}{% endblock %}

{% block main %}
{% comments_for obj %}
{% endblock %}

templates/generic/includes/comments.html
{% load i18n mezzanine_tags comment_tags %}
<div id="comments">
<h3>{% trans "Comments" %}</h3>
{% if settings.COMMENTS_DISQUS_SHORTNAME %}
{% include "generic/includes/disqus_comments.html" %}
{% else %}
<script>
$(function() {
    $('.reply').click(function() {
        $(this).next('.reply-form').toggle();
    });
});
</script>
<style>.input_id_honeypot {display:none !important;}</style>
{% comment_thread object_for_comments %}
<h3>{% trans "New Comment" %}</h3>
<form method="post" id="comment" action="{{ comment_url }}#comment">
    {% if not request.POST.replied_to %}
    {% fields_for posted_comment_form %}
    {% else %}
    {% fields_for unposted_comment_form %}
    {% endif %}
    <div class="form-actions">
        <input class="btn btn-primary btn-large" type="submit" value="{% trans "Send" %}">
    </div>
</form>
{% endif %}
</div>

templates/generic/includes/disqus_counts.html
<script>
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = '{{ settings.COMMENTS_DISQUS_SHORTNAME }}'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

templates/pages/details.html
{% extends "base.html" %}
{% load mezzanine_tags keyword_tags %}

{% block meta_title %}Viddy Details Page{% endblock %}

{#{% block meta_keywords %}{% metablock %}#}
{#{% keywords_for page as keywords %}#}
{#{% for keyword in keywords %}#}
{#    {% if not forloop.first %}, {% endif %}#}
{#    {{ keyword }}#}
{#{% endfor %}#}
{#{% endmetablock %}{% endblock %}#}

{#{% block meta_description %}{% metablock %}#}
{#{{ page.description }}#}
{#{% endmetablock %}{% endblock %}#}

{% block title %}
{{ viddy.title }} (View on browsers: Chrome,  Safari, or IE 9+)
{% endblock %}

{% block breadcrumb_menu %}
<li><a href="/">Home</a><span class="divider">/</span></li>
<li class="active">{{ viddy.title }}</li>
{% endblock %}

{% block extra_css %}
    <style>
        #viddy video{margin: 0 0 0 0; width:640px; height:480px; background-color: black;}
        #stats{float:left; margin: 0 0 0 17px;}
        #viddy{float:left; clear:both;}
        .get_source{clear:both; float:left;}
        .viddy_tags{list-style: none; display: inline; margin: 0 0 0 0; clear:both; float:left;}
        .viddy_tags li{display: inline;}
        .viddy_tags a{border: 1px solid #555; padding: 7px; line-height: 37px;}
    </style>
{% endblock %}

{% block main %}
<div class="get_source">
    <h6><a href="{{ viddy.video_source }}">Source: (Right click HERE and 'Save Link As...')</a></h6>
</div>
<div id="viddy">
    <video autoplay="autoplay" controls="controls">
    <source src="{{ viddy.video_source }}" type="video/mp4">
    Your browser does not support the video tag.
    </video>
</div>
<div id="stats">
    <h4><img src="{{ viddy.viddy_user_thumbnail }}" /> <br />Added by: <a href="http://www.viddy.com/{{ viddy.viddy_user }}" target="_blank">{{ viddy.viddy_user }}</a></h4>
    <h4>Stats for this Viddy:</h4>
    <ul>
    <li>{{ viddy.publish_date }}</li>
    <li>Likes: {{ viddy.like_count }}</li>
    <li>Comments: <a href="http://www.viddy.com/video/{{ viddy.video_id }}" target="_blank">{{ viddy.comment_count }}</a></li>
    </ul>
</div>

<div class="get_source">
    <h6><a href="{{ viddy.video_source }}">Source: (Right click HERE and 'Save Link As...')</a></h6>
</div>

{% if viddy.tag_set.count > 0 %}
<ul class='viddy_tags'>
    <li><strong>TAGS: </strong></li>
    {% for tag in viddy.tag_set.all %}
    <li><a href="/tag/{{ tag.tag_id }}/">{{ tag.tag }}</a></li>
    {% endfor %}
</ul>
{% endif %}
    
{% endblock %}